CREATE TABLE USER_ACCOUNT (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    customer_id NUMBER,
    
    CONSTRAINT fk_user_customer
        FOREIGN KEY (customer_id)
        REFERENCES CUSTOMER(customer_id),

    CONSTRAINT chk_user_role
        CHECK (role IN ('ADMIN', 'CUSTOMER'))
);