CREATE TABLE CUSTOMER (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    phone VARCHAR2(10) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    license_number VARCHAR2(20) UNIQUE NOT NULL
);

CREATE TABLE CATEGORY (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(20) NOT NULL UNIQUE
);

CREATE TABLE BRAND (
    brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE MODEL (
    model_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    brand_id NUMBER NOT NULL,

    category_id NUMBER NOT NULL,

    model_name VARCHAR2(30) NOT NULL,

    CONSTRAINT fk_model_brand
        FOREIGN KEY (brand_id)
        REFERENCES BRAND(brand_id),

    CONSTRAINT fk_model_category
        FOREIGN KEY (category_id)
        REFERENCES CATEGORY(category_id)
);

CREATE TABLE CAR (
    car_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    model_id NUMBER NOT NULL,

    registration_number VARCHAR2(20) NOT NULL UNIQUE,

    manufacturing_year NUMBER(4) NOT NULL,

    price_per_day NUMBER(8,2) NOT NULL,

    status VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,

    CONSTRAINT fk_car_model
        FOREIGN KEY (model_id)
        REFERENCES MODEL(model_id),

    CONSTRAINT chk_car_status
        CHECK (status IN (
            'AVAILABLE',
            'RENTED',
            'MAINTENANCE'
        ))
);

CREATE TABLE BOOKING (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id NUMBER NOT NULL,

    car_id NUMBER NOT NULL,

    start_date DATE NOT NULL,

    end_date DATE NOT NULL,

    total_amount NUMBER(10,2) NOT NULL,

    status VARCHAR2(20) DEFAULT 'BOOKED' NOT NULL,

    CONSTRAINT fk_booking_customer
        FOREIGN KEY (customer_id)
        REFERENCES CUSTOMER(customer_id),

    CONSTRAINT fk_booking_car
        FOREIGN KEY (car_id)
        REFERENCES CAR(car_id),

    CONSTRAINT chk_booking_status
        CHECK (status IN (
            'CONFIRMED',
            'COMPLETED',
            'CANCELLED'
        ))
);

CREATE TABLE PAYMENT (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id NUMBER NOT NULL UNIQUE,

    payment_method VARCHAR2(20) NOT NULL,

    payment_date DATE NOT NULL,

    amount NUMBER(10,2) NOT NULL,

    payment_status VARCHAR2(20) NOT NULL,

    CONSTRAINT fk_payment_booking
        FOREIGN KEY (booking_id)
        REFERENCES BOOKING(booking_id),

    CONSTRAINT chk_payment_method
        CHECK (payment_method IN (
            'UPI',
            'CARD',
            'NET_BANKING',
            'CASH'
        )),

    CONSTRAINT chk_payment_status
        CHECK (payment_status IN (
            'PAID',
            'PENDING',
            'FAILED'
        ))
);